#pragma config(Motor,  port1,           lDrive,        tmotorVex393, openLoop)
#pragma config(Motor,  port2,           lMainArm,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           lSecArm,       tmotorVex393, openLoop)
#pragma config(Motor,  port4,           clawPivot,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port8,           rSecArm,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           rMainArm,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rDrive,        tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "Robot.h"
#include "Macros.h"
#include "Autonomous.c"
#include "UserControl.c"



void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}



task autonomous()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
	  drive(vexRT[Ch3], vexRT[Ch2]);

	  if (vexRT[Btn8U] > 0) {
	  	moveMainLift(TEST_SPEED);
	  }
	  else if (vexRT[Btn8D] > 0) {
	  	moveMainLift(-TEST_SPEED);
	  }
	  else {
	  	moveMainLift(0);
	  }

	  if (vexRT[Btn7U] > 0) {
	  	moveSecLift(TEST_SPEED);
	  }
	  else if (vexRT[Btn7D] > 0) {
	  	moveSecLift(-TEST_SPEED);
	  }
	  else {
	  	moveSecLift(0);
	  }

	  if (vexRT[Btn6U] > 0) {
	  	clampClaw(TEST_SPEED);
	  }
	  else if (vexRT[Btn6D] > 0) {
	  	clampClaw(-TEST_SPEED);
	  }
	  else {
	  	clampClaw(0);
	  }

	  if (vexRT[Btn8R] > 0) {
	  	pivotClaw(TEST_SPEED);
	  }
	  else if (vexRT[Btn8L] > 0) {
	  	pivotClaw(-TEST_SPEED);
	  }
	  else {
	  	pivotClaw(0);
	  }
	}
}
