#pragma config(Sensor, in1,    motor1Up,       sensorTouch)
#pragma config(Sensor, in2,   motor1Down,     sensorTouch)
#pragma config(Sensor, in3,   motor2Up,       sensorTouch)
#pragma config(Sensor, in4,   motor2Down,     sensorTouch)
#pragma config(Sensor, in5,   motor3Up,       sensorTouch)
#pragma config(Sensor, in6,   motor3Down,     sensorTouch)
#pragma config(Sensor, in7,   motor4Up,       sensorTouch)
#pragma config(Sensor, in8,   motor4Down,     sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define motor1 port1
#define motor2 port2
#define motor3 port3
#define motor4 port4



task main()
{
	while(true)
	{

		if(SensorValue[motor1Up]>0)
		{
			motor[motor1]=127;
		}
		else if(SensorValue[motor1Down]>0)
		{
			motor[motor1]=-127;
		}
		else
		{
			motor[motor1]=0;
		}


		if(SensorValue[motor2Up]>0)
		{
			motor[motor2]=127;
		}
		else if(SensorValue[motor2Down]>0)
		{
			motor[motor2]=-127;
		}
		else
		{
			motor[motor2]=0;
		}

		if(SensorValue[motor3Up]>0)
		{
			motor[motor3]=127;
		}
		else if(SensorValue[motor3Down]>0)
		{
			motor[motor3]=-127;
		}
		else
		{
			motor[motor3]=0;
		}

		if(SensorValue[motor4Up]>0)
		{
			motor[motor4]=127;
		}
		else if(SensorValue[motor4Down]>0)
		{
			motor[motor4]=-127;
		}
		else
		{
			motor[motor4]=0;
		}

	}




}
